### ISSUE TITLE
breaks at some items

### ISSUE THREAD

**Issue by kimdiallo** [Uberspace/takeout#13]
```bash
[testkim@andromeda ~]$ uberspace-takeout takeout
writing takeout_testkim_2019-10-30_13_36_57.tar.bz2
takeout: Takeout Marker (internal)
takeout: Homedirectory
takeout: Documentroot
takeout: Cronjobs
Traceback (most recent call last):
  File "/usr/local/bin/uberspace-takeout", line 11, in <module>
    load_entry_point('uberspace-takeout', 'console_scripts', 'uberspace-takeout')()
  File "/opt/takeout/uberspace_takeout/__main__.py", line 29, in main
    Takeout().takeout(tar_path, args.username, args.skip_item)
  File "/opt/takeout/uberspace_takeout/__init__.py", line 57, in takeout
    item.takeout()
  File "/opt/takeout/uberspace_takeout/items/common.py", line 39, in takeout
    cronjobs = self.run_command(['crontab', '-l'])
  File "/opt/takeout/uberspace_takeout/items/base.py", line 29, in run_command
    return [l for l in out.split('\n') if l]
TypeError: a bytes-like object is required, not 'str'
[testkim@andromeda ~]$ 
```

It does not matter if there is a crontab and if it is filled. Same thing happens with Mail and WebDomains.

**Comment by kimdiallo** [comment]
```bash
[testkim@andromeda ~]$ uberspace-takeout takeout --skip-item Cronjobs --skip-item WebDomains
writing takeout_testkim_2019-10-30_13_49_41.tar.bz2
takeout: Takeout Marker (internal)
takeout: Homedirectory
takeout: Documentroot
skip: Cronjobs
takeout: MySQL password
skip: Web Domains
takeout: Mail Domains
Traceback (most recent call last):
  File "/usr/local/bin/uberspace-takeout", line 11, in <module>
    load_entry_point('uberspace-takeout', 'console_scripts', 'uberspace-takeout')()
  File "/opt/takeout/uberspace_takeout/__main__.py", line 29, in main
    Takeout().takeout(tar_path, args.username, args.skip_item)
  File "/opt/takeout/uberspace_takeout/__init__.py", line 57, in takeout
    item.takeout()
  File "/opt/takeout/uberspace_takeout/items/u6.py", line 15, in takeout
    domains = self.run_command(['uberspace-list-domains', self.flag])
  File "/opt/takeout/uberspace_takeout/items/base.py", line 29, in run_command
    return [l for l in out.split('\n') if l]
TypeError: a bytes-like object is required, not 'str'
[testkim@andromeda ~]$
```
