### ISSUE TITLE
Streaming does not work anymore 

### ISSUE THREAD

**Issue by kimdiallo** [Uberspace/takeout#14]
```bash
[testkim@andromeda ~]$ uberspace-takeout takeout --skip-item Cronjobs --skip-item WebDomains --skip-item MailDomain --tar-file - | ssh ziggy@stardust.uberspace.de "uberspace-takeout takein --tar-file -"
writing /dev/stdout
takeout: Takeout Marker (internal)
takeout: Homedirectory
reading /dev/stdin
takein: Takeout Marker (internal)
Traceback (most recent call last):
  File "/usr/bin/uberspace-takeout", line 11, in <module>
    load_entry_point('uberspace-takeout', 'console_scripts', 'uberspace-takeout')()
  File "/opt/takeout/uberspace_takeout/__main__.py", line 35, in main
    Takeout().takein(tar_path, args.username, args.skip_item)
  File "/opt/takeout/uberspace_takeout/__init__.py", line 47, in takein
    item.takein()
  File "/opt/takeout/uberspace_takeout/items/common.py", line 13, in takein
    content = self.storage.unstore_text('.uberspace_takeout')
  File "/opt/takeout/uberspace_takeout/storage.py", line 142, in unstore_text
    if not self.has_member(storage_path):
  File "/opt/takeout/uberspace_takeout/storage.py", line 94, in has_member
    for m in self.tar.getmembers():
  File "/opt/takeout/lib64/python3.6/tarfile.py", line 1761, in getmembers
    self._load()        # all members, we first have to
  File "/opt/takeout/lib64/python3.6/tarfile.py", line 2358, in _load
    tarinfo = self.next()
  File "/opt/takeout/lib64/python3.6/tarfile.py", line 2289, in next
    self.fileobj.seek(self.offset - 1)
  File "/usr/lib64/python3.6/bz2.py", line 277, in seek
    self._check_can_seek()
  File "/usr/lib64/python3.6/_compression.py", line 29, in _check_can_seek
    raise io.UnsupportedOperation("The underlying file object "
io.UnsupportedOperation: The underlying file object does not support seeking
Traceback (most recent call last):
  File "/opt/takeout/uberspace_takeout/__init__.py", line 57, in takeout
    item.takeout()
  File "/opt/takeout/uberspace_takeout/items/base.py", line 39, in takeout
    self.storage.store_directory(self.path(), self.storage_path)
  File "/opt/takeout/uberspace_takeout/storage.py", line 42, in store_directory
    return self.store_file(system_path, storage_path)
  File "/opt/takeout/uberspace_takeout/storage.py", line 150, in store_file
    self.tar.add(str(system_path), storage_path)
  File "/opt/takeout/lib/python3.6/tarfile.py", line 1959, in add
    recursive, exclude, filter=filter)
  File "/opt/takeout/lib/python3.6/tarfile.py", line 1959, in add
    recursive, exclude, filter=filter)
  File "/opt/takeout/lib/python3.6/tarfile.py", line 1959, in add
    recursive, exclude, filter=filter)
  [Previous line repeated 6 more times]
  File "/opt/takeout/lib/python3.6/tarfile.py", line 1952, in add
    self.addfile(tarinfo, f)
  File "/opt/takeout/lib/python3.6/tarfile.py", line 1980, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
  File "/opt/takeout/lib/python3.6/tarfile.py", line 252, in copyfileobj
    dst.write(buf)
  File "/package/host/localhost/python-3.6/lib/python3.6/bz2.py", line 246, in write
    self._fp.write(compressed)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/uberspace-takeout", line 11, in <module>
    load_entry_point('uberspace-takeout', 'console_scripts', 'uberspace-takeout')()
  File "/opt/takeout/uberspace_takeout/__main__.py", line 29, in main
    Takeout().takeout(tar_path, args.username, args.skip_item)
  File "/opt/takeout/uberspace_takeout/__init__.py", line 57, in takeout
    item.takeout()
  File "/opt/takeout/uberspace_takeout/storage.py", line 56, in __exit__
    self.tar.close()
  File "/opt/takeout/lib/python3.6/tarfile.py", line 1742, in close
    self.fileobj.close()
  File "/package/host/localhost/python-3.6/lib/python3.6/bz2.py", line 125, in close
    self._fp.write(self._compressor.flush())
BrokenPipeError: [Errno 32] Broken pipe
[testkim@andromeda ~]$
```

**Comment by luto** [comment]
streaming support is reenabled, but it seems like we're running into https://bugs.python.org/issue12800 :/

**Comment by luto** [comment]
oh, no, it's this. So I'm holding it wrong. https://bugs.python.org/issue10436
