### ISSUE TITLE
takeout bails on UTF-8 characters in .my.cnf

### ISSUE THREAD

**Issue by jonmz** [Uberspace/takeout#23]
In most `.my.cnf` files the password line reads like this:

```
password=blablabla # NICHT ÄNDERN
```

The "Ä" is encoded as UTF-8 (hex c3 84):

```
$ hexdump -C .my.cnf | grep NDERN
000003d0  20 c3 84 4e 44 45 52 4e  21 0a 70 6f 72 74 3d 33  | ..NDERN!.port=3|
00000440  c3 84 4e 44 45 52 4e 2c  20 6f 68 6e 65 20 64 65  |..NDERN, ohne de|
```
Unfortunately, `uberspace-takeout` bails on this:
```
$ /package/host/localhost/python-3.6.10/bin/uberspace-takeout takeout
[...]
takeout: MySQL password
Traceback (most recent call last):
  File "/package/host/localhost/python-3.6.10/bin/uberspace-takeout", line 11, in <module>
    load_entry_point('uberspace-takeout==0.0.3', 'console_scripts', 'uberspace-takeout')()
  File "/package/host/localhost/python-3.6.10/lib/python3.6/site-packages/uberspace_takeout/__main__.py", line 29, in main
    Takeout().takeout(tar_path, args.username, args.skip_item)
  File "/package/host/localhost/python-3.6.10/lib/python3.6/site-packages/uberspace_takeout/__init__.py", line 61, in takeout
    item.takeout()
  File "/package/host/localhost/python-3.6.10/lib/python3.6/site-packages/uberspace_takeout/items/common.py", line 82, in takeout
    self.storage.store_text(self._read_my_cnf_password('client'), 'conf/mysql-password-client')
  File "/package/host/localhost/python-3.6.10/lib/python3.6/site-packages/uberspace_takeout/items/common.py", line 66, in _read_my_cnf_password
    raw_pw = self._open_my_cnf(section)[section]['password']
  File "/package/host/localhost/python-3.6.10/lib/python3.6/site-packages/uberspace_takeout/items/common.py", line 62, in _open_my_cnf
    config.read(self._my_cnf_path)
  File "/package/host/localhost/python-3.6.10/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/package/host/localhost/python-3.6.10/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/package/host/localhost/python-3.6.10/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 977: ordinal not in range(128)
```

According to the [docs for ConfigParser.read](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read) that method now accepts an optional `encoding` setting, so it might be sufficient to change:

        config.read(self._my_cnf_path)

into

        config.read(self._my_cnf_path, encoding='utf-8')

in `items/common.py`.

**Comment by luto** [comment]
py2 support will be dropped in the next release.

**Comment by brutus** [comment]
Closed by https://github.com/Uberspace/takeout/pull/28
