### ISSUE TITLE
takin on U7 breaks because of Grünkohl

### ISSUE THREAD

**Issue by kimdiallo** [Uberspace/takeout#24]
There is an encoding error: 

```bash 
Traceback (most recent call last):
  File "/opt/uberspace/python-venv/bin/uberspace-takeout", line 11, in <module>
    sys.exit(main())
  File "/opt/uberspace/python-venv/lib/python2.7/site-packages/uberspace_takeout/__main__.py", line 35, in main
    Takeout().takein(tar_path, args.username, args.skip_item)
  File "/opt/uberspace/python-venv/lib/python2.7/site-packages/uberspace_takeout/__init__.py", line 49, in takein
    item.takein()
  File "/opt/uberspace/python-venv/lib/python2.7/site-packages/uberspace_takeout/items/common.py", line 50, in takein
    self.run_command(['crontab', '-'], input_text=text)
  File "/opt/uberspace/python-venv/lib/python2.7/site-packages/uberspace_takeout/items/base.py", line 28, in run_command
    out, _ = p.communicate(input_text)
  File "/usr/lib64/python2.7/subprocess.py", line 800, in communicate
    return self._communicate(input)
  File "/usr/lib64/python2.7/subprocess.py", line 1401, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib64/python2.7/subprocess.py", line 1465, in _communicate_with_poll
    input_offset += os.write(fd, chunk)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 244: ordinal not in range(128)
```

Because of an Ü on the crontab: 

```bash
[salocin@vega ~]$ crontab -l
@daily ~/bin/qdated/get_new_mail.sh
@daily ~/bin/qdated/remove_expired_trashmails.sh
@daily /usr/local/bin/uberspace-letsencrypt-renew

@weekly lynx -dump https://www.stw-bremen.de/de/essen-trinken/mensa-werderstra\%C3\%9Fe  | grep -E "(Brau|Gr(ü|&uuml;))nkohl"
@weekly lynx -dump https://www.stw-bremen.de/de/essen-trinken/mensa-neustadtswall | grep -E "(Brau|Gr(ü|&uuml;))nkohl"
@weekly lynx -dump https://www.stw-bremen.de/de/essen-trinken/uni-mensa | grep -E "(Brau|Gr(ü|&uuml;))nkohl"
@weekly lynx -dump https://www.stw-bremen.de/de/essen-trinken/mensa-am-airport | grep -E "(Brau|Gr(ü|&uuml;))nkohl"
[salocin@vega ~]$
```

**Comment by luto** [comment]
py2 support will be dropped in the next release.

**Comment by brutus** [comment]
See https://github.com/Uberspace/takeout/pull/28 and https://github.com/Uberspace/takeout/pull/29
