### ISSUE TITLE
takeout on U7 fails on rust

### ISSUE THREAD

**Issue by luto** [Uberspace/takeout#35]
```
$ uberspace tools version show rust
No version set for 'Rust', using default: 'stable'
```

```
takeout: Setting: Tool Versions
Traceback (most recent call last):
  File "/opt/uberspace/commands/uberspace-takeout", line 11, in <module>
    sys.exit(main())
  File "/opt/uberspace/python-venv-3.6/lib/python3.6/site-packages/uberspace_takeout/__main__.py", line 32, in main
    t.takeout(tar_path, args.username, args.skip_item)
  File "/opt/uberspace/python-venv-3.6/lib/python3.6/site-packages/uberspace_takeout/__init__.py", line 69, in takeout
    item.takeout()
  File "/opt/uberspace/python-venv-3.6/lib/python3.6/site-packages/uberspace_takeout/items/u7.py", line 108, in takeout
    version = re.search(r"'([0-9\.]+)'", out[0]).groups()[0]
AttributeError: 'NoneType' object has no attribute ‘groups’
```

`"stable"` does not match `[0-9\.]+`.

**Comment by luto** [comment]
Takeout will likely be rewritten after the EOL on U6, so it's unclear, if we'll fix this.

**Comment by noave** [comment]
use `--skip-item rust` to workaround this problem

**Comment by erikw** [comment]
For me, there was further problems than rust and the workaround was to skip all tool versions:

```cmd
$ uberspace takeout takeout --skip-item ToolVersions
```
